apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook-frontend
  name: guestbook-frontend
spec:
  ports:
  - name: tcp-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-frontend
  type: NodePort
status:
  loadBalancer: {}
